# Generated by Django 2.1.4 on 2019-03-05 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20190305_2247'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
